[features]
seeds = false
skip-lint = false
[programs.localnet]
ftrx_swap = "2DpiziPDmTsZStzv7qtRfsetz2Dx1zCcronBKx2Jq192"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "tests/testKeys/superUser.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10_000_000